name: front-end-ci

on:
  # Manual trigger
  workflow_dispatch:

  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    types: [opened, synchronize, closed]
    branches: [ main, dev]
  
env:
  # Set Node.js Version
  NODE_VERSION: '18.x'

jobs:

  install-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/frontend
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('starter/frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: ${{env.NODE_VERSION}}
    
    - name: Instal, Lint
      run: | 
        npm ci
        npm run lint

  install-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/frontend
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('starter/frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: ${{env.NODE_VERSION}}
    
    - name: Install, Test
      run: | 
        npm ci
        npm run test 

  install-build:
    needs: [install-test, install-lint]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/frontend
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: ${{env.NODE_VERSION}}

    - name: Install, Build
      run: | 
        npm ci
        npm run build --if-present